name: Upload Website

on:
   #[workflow_dispatch]       # Used for manual testing
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest # spins up box for free on github
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build -- --prod
    - uses: actions/checkout@master
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run: aws s3 sync dist/personalWebsite s3://mattfishman.com --acl public-read --follow-symlinks --delete

